# Generated by Django 6.0.6 on 2026-07-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calory_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='brm',
            field=models.FloatField(null=True),
        ),
    ]
