# Generated by Django 6.0.6 on 2026-07-13 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calory_App', '0002_profilemodel_brm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='brm',
            new_name='bmr',
        ),
    ]
