# Generated by Django 6.0.6 on 2026-07-13 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calory_App', '0003_rename_brm_profilemodel_bmr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='bmr',
        ),
    ]
